-- Для @GeneratedValue(strategy = GenerationType.IDENTITY)
/*
create table client
(
    id   bigserial not null primary key,
    name varchar(50)
);

 */

-- Для @GeneratedValue(strategy = GenerationType.SEQUENCE)
create sequence hibernate_sequence start with 1 increment by 1;

create table client
(
    id   bigint not null primary key,
    name varchar(50),
    address_id bigint
);

create table address (
    id bigint generated by default as identity primary key,
    country varchar(50) not null,
    region varchar(50),
    city varchar(50),
    street varchar(50),
    house_number integer,
    building_number integer,
    apartment_number integer
);